# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '知识点验证合集' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'Aspects'
  pod 'AFNetworking'
  pod 'SDWebImage'

  target '知识点验证合集Tests' do
    inherit! :search_paths
    pod 'Aspects'
    pod 'AFNetworking'
    pod 'SDWebImage'
  end

  target '知识点验证合集UITests' do
    inherit! :search_paths
    pod 'Aspects'
    pod 'AFNetworking'
    pod 'SDWebImage'
  end

end
